# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      # specify the postgres version used here
      - image: circleci/postgres:9.6
        environment:
          - POSTGRES_USER=samuel
          - POSTGRES_DB=event_test
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    # simply a place where the code shall be checked out and ran 
    working_directory: ~/workspace

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # install sequelize globally    
      - run:
          name: Install sequelize 
          command: 'sudo npm install -g sequelize-cli'

      # run tests!
      - run: 
          name: Run Tests
          command: npm test